### PR TITLE
Support Async Elements

### PR DESCRIPTION
**Pull request by CollinValley**
This is a rather large pull request. It creates a basic Async Element that can be strung together with Sync elements to for a basic serial chain of computation.  See the commit message and it's implementation for more.  It is still a bit rough, and I expect there to be further changes when we add support for reactors to the elements. But this is a good start.  I also included some changes to the Readme, again it is a little rough, but I wanted to get some foundations laid down.

### CODE REVIEW

**Review by ddowl — CHANGES_REQUESTED** [review]
This commit seems distinct enough that it should be in a separate PR. Is that relatively easy to do?

**Review by ddowl — COMMENTED** [review]
A few minor comments:

1. Check the spelling/spacing in the commit message.
2. It might be worth breaking up this commit into several: one that adds the `ForeverDrain`, one that renames `ElementLink`'s structure, and one that adds the spsc Async Element implementation.

Definitely go over the commit message, but you don't have to split up the commit if you don't feel like it.

**Comment by CollinValley** [comment]
I think, for the sake of my own laziness, I'm going to leave these two together as one PR, in the future though I will separate them.

**Comment by CollinValley** [comment]
So in the interest of my own laziness, I'm not going to break this up into multiple commits. This is mostly because we have a few lines that would have been changed in one commit, then changed again in the next commit, and I don't want to go through and rectify them.  I did clean up the commit messages for each, and also fixed a few spelling errors and grammar in the README.md.  At this point I am going to commit the pull request.  In the future, we will only take smaller commits that are better formatted,  especially as the codebase starts to grow beyond just three files.

**Pull request merged**
